name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: 'yarn:install'
        run: yarn install
        env:
          CI: true
      - name: build
        run: yarn build
